package model

type BusinessOrder struct {
	ResultStat string `json:"resultStat"`
	Mess       string `json:"mess"`
	Data       struct {
		Values     []BusinessOrderValue `json:"values"`
		Pagenation struct {
			PageSize  int `json:"pageSize"`
			PageNo    int `json:"pageNo"`
			ItemCount int `json:"itemCount"`
			PageCount int `json:"pageCount"`
		} `json:"pagenation"`
	} `json:"data"`
}

type BusinessOrderValue struct {
	Id                    int64  `json:"id"`
	ProId                 string `json:"proId"`
	ParentProdId          string `json:"parentProdId"`
	ProCls                string `json:"proCls"`
	ProType               string `json:"proType"`
	SystemSource          string `json:"systemSource"`
	SystemType            string `json:"systemType"`
	BusinessType          string `json:"businessType"`
	ProLevel              int    `json:"proLevel"`
	ProPri                string `json:"proPri"`
	ProTitle              string `json:"proTitle"`
	ProContent            string `json:"proContent"`
	CustomerName          string `json:"customerName"`
	CustomerPhone         string `json:"customerPhone"`
	AskTime               string `json:"askTime"`
	Province              string `json:"province"`
	City                  string `json:"city"`
	CurrentActionId       string `json:"currentActionId"`
	ProState              int    `json:"proState"`
	ProSonState           int    `json:"proSonState"`
	IsSolve               string `json:"isSolve"`
	IsSatisfaction        string `json:"isSatisfaction"`
	ProcessPro            string `json:"processPro"`
	ProcessCity           string `json:"processCity"`
	ProcessorId           string `json:"processorId"`
	Processor             string `json:"processor"`
	ProResult             string `json:"proResult"`
	FromProId             string `json:"fromProId"`
	CurrentProcessor      string `json:"currentProcessor"`
	CurrentProcessorId    string `json:"currentProcessorId"`
	CurrentProcessorPhone string `json:"currentProcessorPhone"`
	FinishTime            string `json:"finishTime"`
	Isvalid               string `json:"isValid"`
	CreatorId             string `json:"creatorId"`
	Creator               string `json:"creator"`
	CreatorName           string `json:"creatorName"`
	CreatorPro            string `json:"creatorPro"`
	CreatorCity           string `json:"creatorCity"`
	ExpectedOverTime      string `json:"expectedOverTime"`
	CreateTime            string `json:"createTime"`
	UpdateTime            string `json:"updateTime"`
	IsCallBack            string `json:"isCallBack"`
	SolvedScore           int    `json:"solvedScore"`
	ProClassify           string `json:"proClassify"`
	ReturnVisit           string `json:"returnVisit"`
	IsReturnVisit         string `json:"isReturnVisit"`
	IfPutThrough          string `json:"ifPutThrough"`
	ReturnVisitCount      int    `json:"returnVisitCount"`
	IfSecrecy             string `json:"ifSecrecy"`
	IfDelayed             string `json:"ifDelayed"`
	IfUp                  string `json:"ifUp"`
	DelayedReason         string `json:"delayedReason"`
	ExpectTime            string `json:"expectTime"`
	UpgradeTime           string `json:"upgradeTime"`
	ExpectOnlineTime      string `json:"expectOnlineTime"`
	HandleNum             int    `json:"handleNum"`
	TeamType              int    `json:"teamType"`
	OtherLabel            int    `json:"otherLabel"`
	OtherLabelName        string `json:"otherLabelName"`
	OnlineTime            string `json:"onlineTime"`
	FirstRespTime         string `json:"firstRespTime"`
	ProvinceName          string `json:"provinceName"`
	CityName              string `json:"cityName"`
	CreatorProName        string `json:"creatorProName"`
	CreatorCityName       string `json:"creatorCityName"`
	SystemSourceName      string `json:"systemSourceName"`
	ProStateName          string `json:"proStateName"`
	ProLevelName          string `json:"proLevelName"`
	ProTypeName           string `json:"proTypeName"`
	BusinessTypeName      string `json:"businessTypeName"`
	ProClsName            string `json:"proClsName"`
	Name                  string `json:"name"`
	Phone                 string `json:"phone"`
	CreatorPhone          string `json:"creatorPhone"`
	PartCreateTime        string `json:"partCreateTime"`
	PushIT                bool   `json:"pushIT"`
	PushTwoWings          bool   `json:"pushTwoWings"`
	LiftLockType          string `json:"liftLockType"`
	ExpectOnlineVersion   string `json:"expectOnlineVersion"`
	WhichSystem           string `json:"whichSystem"`
	ChildWhichSystem      string `json:"childWhichSystem"`
	EnableSplit           bool   `json:"enableSplit"`
	EnableProcess         bool   `json:"enableProcess"`
	IfOperation           bool   `json:"ifOperation"`
	WhichPlatformName     string `json:"whichPlatformName"`
	NoHtmlProContent      bool   `json:"noHtmlProContent"`
	Aging                 int    `json:"aging"`
	OtherCode             string `json:"otherCode"`
	BugType               string `json:"bugType"`
	BugTypeName           string `json:"bugTypeName"`
	CloseName             string `json:"closeName"`
	ProblemSourceName     string `json:"problemSourceName"`
	FlowTaskProblemVo     struct {
		ProcessDefId string `json:"processDefId"`
		DefinitionId string `json:"definitionId"`
		TaskKey      string `json:"taskKey"`
		TaskName     string `json:"taskName"`
		PushIt       bool   `json:"pushIt"`
		PushTwoWings bool   `json:"pushTwoWings"`
		RevertType   string `json:"revertType"`
		SplitType    int    `json:"splitType"`
	} `json:"flowTaskProblemVo"`
	ProTaskState     int    `json:"proTaskState"`
	SystemCode       string `json:"systemCode"`
	SystemCodeName   string `json:"systemCodeName"`
	DispatchDuration string `json:"dispatchDuration"`
	IntegratedUserId string `json:"integratedUserId"`
	OperationUserId  string `json:"operationUserId"`
	ZenTaoProblem    struct {
		PageSize        int    `json:"pageSize"`
		PageNum         int    `json:"pageNum"`
		PageNo          int    `json:"pageNo"`
		IsExport        bool   `json:"isExport"`
		Enable          bool   `json:"enable"`
		Id              any    `json:"id"`
		ParentCode      string `json:"parentCode"`
		BugId           string `json:"bugId"`
		Product         string `json:"product"`
		Module          string `json:"module"`
		ModuleName      string `json:"moduleName"`
		OpenedBuild     string `json:"openedBuild"`
		OpenedBuildName string `json:"openedBuildName"`
		Type            string `json:"type"`
		TypeName        string `json:"typeName"`
		Os              string `json:"os"`
		Title           string `json:"title"`
		Severity        int    `json:"severity"`
		SeverityName    string `json:"severityName"`
		CreateTime      string `json:"createTime"`
		UpdateTime      string `json:"updateTime"`
		IsLock          bool   `json:"isLock"`
	} `json:"zenTaoProblem"`
	OpenedBuild     string `json:"openedBuild"`
	OpenedBuildName string `json:"openedBuildName"`
	LastUpdate      string `json:"lastUpdate"`
	CloseTime       string `json:"closeTime"`
	SolveType       int    `json:"solveType"`
	SolveTypeName   string `json:"solveTypeName"`
	ProblemSource   string `json:"problemSource"`
}
